resources:
- name: bosh
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh

- name: bosh-agent
  type: git
  source:
    uri: git@github.com:mattcui/bosh-agent.git
    branch: bm_beta
    private_key: {{private-repo-key}}

- name: bats
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-acceptance-tests.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-cpi
  type: git
  source:
    uri: git@github.com:karafelix/bosh-softlayer-cpi.git
    branch: kara_updates
    private_key: {{private-repo-key}}

- name: bat-release-artifact
  type: s3
  source:
    regexp: bat\.tgz
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
 
- name: s3-vsphere-stemcell
  type: s3
  source:
    regexp: bosh-stemcell-(.*)-vsphere-esxi-ubuntu-trusty-go_agent\.tgz
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: light-stemcell
  type: s3
  source:
    regexp: light-bosh-stemcell-\d+-softlayer-.*\.tgz
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: bosh-softlayer-cpi-release
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-cpi-release.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-private
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-private.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-stemcells
  type: git
  source:
    uri: git@github.com:karafelix/bosh-softlayer-stemcells.git
    branch: bosh-init
    private_key: {{private-repo-key}}

- name: bosh-stemcell-softlayer-image
  type: s3
  source:
    regexp: bosh-stemcell-softlayer.vhd
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: final-release
  type: s3
  source:
    regexp: bosh-softlayer-cpi-release-(.*).tgz
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: softlayer-go
  type: git
  source:
    uri: git@github.com:maximilien/softlayer-go.git
    branch: master
    private_key: {{private-repo-key}}

- name: version
  type: semver
  source:
    bucket: {{s3-bucket}}
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

- name: stemcell-version
  type: s3
  source:
    bucket: {{s3-bucket}}
    versioned_file: stemcell-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: softlayer-stemcell
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: bosh-stemcell-(.*)-vsphere-(.*).tgz
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: stemcell-info
  type: s3
  source:
    bucket: {{s3-bucket}}
    versioned_file: stemcell-info.json
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

- name: timer-2weeks
  type: time
  source:
    interval: 336h

jobs:
- name: bosh-stemcell
  plan:
  - aggregate:
    - get: bosh
    - get: bosh-softlayer-stemcells
    - get: bosh-softlayer-private
    - get: vsphere-stemcell
      trigger: true
  - task: bosh-stemcell
    file: bosh-softlayer-stemcells/ci/bosh-stemcell.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{BOSH_AWS_ACCESS_KEY_ID}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{BOSH_AWS_SECRET_ACCESS_KEY}}
        BOSH_VAGRANT_KEY_PATH: ../../bosh-softlayer-private/bosh.pem
        AWS_ACCESS_KEY: {{BOSH_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: {{BOSH_AWS_SECRET_ACCESS_KEY}}
  - aggregate:
    - put: stemcell-version
      params: {from: out/stemcell-version}
    - put: s3-vsphere-stemcell
      params: {from: out/bosh-stemcell-.*-vsphere-.*\.tgz}

- name: convert-stemcell
  plan:
  - get: s3-vsphere-stemcell
    trigger: true
    passed: [bosh-stemcell]
  - get: bosh-softlayer-stemcells
  - get: stemcell-version
    trigger: true
    passed: [bosh-stemcell]
  - task: convert-stemcell
    file: bosh-softlayer-stemcells/ci/convert-stemcell.yml
    config:
      params:
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_API_KEY: {{SL_API_KEY}}
        SWIFT_CLUSTER: {{SWIFT_CLUSTER}}

- name: cpi-unit
  public: true
  plan:
  - get: bosh-softlayer-cpi
    trigger: true
  - task: unit
    file: bosh-softlayer-cpi/ci/unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key

- name: cpi-integration
  plan:
  - get: bosh-softlayer-cpi
    trigger: true
    passed: [cpi-unit]
  - task: build
    file: bosh-softlayer-cpi/ci/build.yml
  - task: integration
    file: bosh-softlayer-cpi/ci/integration.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        SL_DATACENTER: {{SL_DATACENTER}}
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_CLUSTER: {{SWIFT_CLUSTER}}

- name: cpi-build
  plan:
  - get: bosh-softlayer-cpi
    trigger: true
    passed: [cpi-integration]
  - task: build
    file: bosh-softlayer-cpi/ci/build.yml

- name: cpi-release-rc
  serial: true
  plan:
  - get: bosh-softlayer-cpi-release
    trigger: true
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: cpi-release-shipit
  serial: true
  plan:
  - aggregate:
    - get: bosh-softlayer-private
    - get: bosh-softlayer-stemcells
    - get: bosh-softlayer-cpi
      passed: [cpi-build]
      trigger: true
    - get: bosh-softlayer-cpi-release
      passed: [cpi-release-rc]
      params: {submodules: none}
    - get: version
      passed: [cpi-release-rc]
      params: {bump: final}
  - task: create-final-release
    file: bosh-softlayer-stemcells/ci/cpi-release-shipit.yml
  - aggregate:  
    - put: final-release
      params: {from: create-final-release/bosh-softlayer-cpi-release-.*.tgz}
    - put: version
      params: {file: version/number}

- name: create-light-stemcell
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
      passed: [import-stemcell]
    - get: stemcell-info
      trigger: true
      passed: [import-stemcell]
    - get: stemcell-version
    passed: [import-stemcell]
  - task: create-light-stemcell
    file: bosh-softlayer-stemcells/ci/create-light-stemcell.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
  - put: light-stemcell
    params: {from: .*\.tgz}

- name: bosh-init
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
    - get: bosh-release
    - get: light-stemcell
      passed: [create-light-stemcell]
    - get: bosh-agent
    - get: final-release
      passed: [cpi-release-shipit]
  - task: bosh-init
    file: bosh-softlayer-stemcells/ci/bosh-init.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        SL_DATACENTER: {{SL_DATACENTER}}
        SL_VLAN_PUBLIC: {{SL_VLAN_PUBLIC}}
        SL_VLAN_PRIVATE: {{SL_VLAN_PRIVATE}}

- name: generate-bat-release
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
    - get: bats
  - task: generate-bat-release
    file: bosh-softlayer-stemcells/ci/generate-bat-release.yml
  - put: bat-release-artifact
    params: {from: out/.*\.tgz}

- name: bats
  serial: true
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
    - get: bats
    - get: bosh-release
    - get: final-release
      passed: [cpi-release-shipit]
      trigger: true
    - get: light-stemcell
      passed: [create-light-stemcell]
      trigger: true
    - get: bat-release-artifact
      passed: [generate-bat-release]
  - try:
      task: upload-bat-release
      file: bosh-softlayer-stemcells/ci/upload-bat-release.yml
      config:
        params:
          director_target: {{director_target}}
          director_user: {{director_user}}
          director_password: {{director_password}}
  - task: bats
    file: bosh-softlayer-stemcells/ci/bats.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        director_target: {{director_target}}
        director_user: {{director_user}}
        director_password: {{director_password}}

- name: remove-expiration-tag
  plan:
  - get: bosh-softlayer-stemcells
    trigger: true
    passed: [shipit]
  - task: remove-expiration-tag-vhd
    file: bosh-softlayer-stemcells/ci/remove-expiration.yml
    config:
      params:
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_API_KEY:  {{SL_API_KEY}}
        SWIFT_CLUSTER:  {{SWIFT_CLUSTER}}
        S3_ACCESS_KEY:  {{s3-access-key-id}}
        S3_SECRET_KEY:  {{s3-secret-access-key}}

- name: import-stemcell
  plan:
  - get: bosh-softlayer-stemcells
  - get: stemcell-version
    trigger: true
    passed: [convert-stemcell]
  - task: import-stemcell-image
    file: bosh-softlayer-stemcells/ci/import-stemcell.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_CLUSTER: {{SWIFT_CLUSTER}}
  - put: stemcell-info
    params: {from: import-stemcell-image/stemcell-info.json}

- name: stemcells-unit
  public: true
  plan:
  - get: bosh-softlayer-stemcells
    trigger: true
  - task: unit
    file: bosh-softlayer-stemcells/ci/unit.yml

- name: sl-go-unit
  public: true
  plan:
  - get: softlayer-go
    trigger: true
  - task: unit
    file: softlayer-go/ci/unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key

- name: sl-go-integration
  plan:
  - get: softlayer-go
    trigger: true
    passed: [sl-go-unit]
  - task: integration
    file: softlayer-go/ci/integration.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        SL_DATACENTER: {{SL_DATACENTER}}

- name: cleanup-stemcells
  plan:
  - get: bosh-softlayer-stemcells
  - get: timer-2weeks
    trigger: true
  - task: cleanup-stemcells-VGBTG
    file: bosh-softlayer-stemcells/ci/cleanup-stemcells.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}

- name: shipit
  plan:
  - get: bosh-softlayer-stemcells
    passed: [bats]
  - get: final-release
    passed: [cpi-release-shipit]
  - get: version
    passed: [cpi-release-shipit]
  - get: stemcell-info
    passed: [create-light-stemcell]
  - task: shipit-stemcells-and-cpi
    file: bosh-softlayer-stemcells/ci/shipit.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        S3_ACCESS_KEY: {{s3-access-key-id}}
        S3_SECRET_KEY: {{s3-secret-access-key}}

groups:
- name: all
  jobs:
  - bosh-stemcell
  - convert-stemcell
  - create-light-stemcell
  - cpi-unit
  - cpi-integration
  - cpi-build
  - cpi-release-rc
  - cpi-release-shipit
  - import-stemcell
  - stemcells-unit
  - sl-go-unit
  - sl-go-integration
  - cleanup-stemcells
  - remove-expiration-tag
  - bosh-init
  - generate-bat-release
  - bats
  - shipit

- name: bosh-softlayer-cpi
  jobs:
  - cpi-unit
  - cpi-integration
  - cpi-build

- name: bosh-softlayer-cpi-release
  jobs:
  - cpi-release-rc
  - cpi-release-shipit

- name: bosh-softlayer-stemcells
  jobs:
  - bosh-stemcell
  - convert-stemcell
  - create-light-stemcell
  - import-stemcell
  - stemcells-unit

- name: softlayer-go
  jobs:
  - sl-go-unit
  - sl-go-integration

- name: shipit
  jobs:
  - shipit
  - remove-expiration-tag
  - cleanup-stemcells

- name: bosh-init
  jobs:
  - bosh-init
  - bats
