#!/bin/bash

set -e

pushd light-stemcell
    LIGHT_STEMCELL=`ls *.tgz`
    STEMCELL_PATH=$PWD/$LIGHT_STEMCELL
popd

cp bosh-softlayer-stemcells/templates/softlayer.yml.erb bats/templates/

cd bats
./write_gemfile

# echo "Installing gems..."
bundle install

bosh -n target $director_target
bosh -n login $director_user $director_password

director_uuid=$(bosh -n status --uuid)

spec_path=$PWD/bat.spec

# Create bat.spec used by BATS to generate BOSH manifest
cat > $spec_path << EOF
---
cpi: softlayer
properties:
  static_ip: 10.244.0.2
  uuid: $director_uuid
  pool_size: 1
  instances: 1
  stemcell:
    name: ${LIGHT_STEMCELL%.*}
    version: latest
  mbus: nats://nats:0b450ada9f830085e2cdeff6@10.42.49.80:4222
  networks:
  - name: default
    type: dynamic
    dns: [8.8.8.8, 10.0.80.11, 10.0.80.12]
    cloud_properties:
    security_groups: [bosh]
EOF

# Set up env vars used by BATS
export BAT_DEPLOYMENT_SPEC=$spec_path
export BAT_STEMCELL=$STEMCELL_PATH
export BAT_DIRECTOR=$director_target
export BAT_DNS_HOST=$director_target
export BAT_VCAP_PASSWORD=c1oudc0w

export BAT_INFRASTRUCTURE=warden
export BAT_NETWORKING=manual

echo "running BATS..."
bundle exec rspec spec
