#!/bin/bash

set -e

base=$( cd "$( dirname "$( dirname "$( dirname "$0" )")")" && pwd )
base_gopath=$( cd $base/../../../.. && pwd )

export GOPATH=$base/Godeps/_workspace:$base_gopath:$GOPATH

gem uninstall -ax bosh_cli --force

gem install bosh_cli -v '1.2650.0' --no-rdoc --no-ri

cat -b /var/lib/gems/2.1.0/gems/bosh_cli-*/lib/cli/commands/release.rb

cd gopath/src/github.com/cloudfoundry/bosh-acceptance-tests
./write_gemfile

# echo "Installing gems..."
bundle install

echo -e "\n Get stemcell version..."
s3cmd get s3://bosh-softlayer-cpi-stemcells/stemcell-version stemcell-version --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY
STEMCELL_VERSION=`cat stemcell-version`

echo $STEMCELL_VERSION

LIGHT_STEMCELL=light-bosh-stemcell-$STEMCELL_VERSION-softlayer-esxi-ubuntu-trusty-go_agent.tgz

echo "Downloading $LIGHT_STEMCELL..."
s3cmd get s3://bosh-softlayer-cpi-stemcells/$LIGHT_STEMCELL --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY

STEMCELL_PATH=$PWD/$LIGHT_STEMCELL

director_target=173.193.4.40
director_user=admin
director_password=admin

bosh -n target $director_target
bosh -n login $director_user $director_password

director_uuid=$(bosh -n status --uuid)

spec_path=$PWD/bat.spec

# Create bat.spec used by BATS to generate BOSH manifest
cat > $spec_path << EOF
---
cpi: softlayer
properties:
static_ip: 10.244.0.2
uuid: $director_uuid
pool_size: 1
instances: 1
stemcell:
  name: ${LIGHT_STEMCELL%.*}
  version: latest
mbus: nats://nats:0b450ada9f830085e2cdeff6@10.42.49.80:4222
networks:
- name: default
  type: dynamic
  dns: [8.8.8.8, 10.0.80.11, 10.0.80.12]
  cloud_properties:
    security_groups: [bosh]
EOF

# Set up env vars used by BATS
export BAT_DEPLOYMENT_SPEC=$spec_path
export BAT_STEMCELL=$STEMCELL_PATH
export BAT_DIRECTOR=$director_target
export BAT_DNS_HOST=$director_target
export BAT_VCAP_PASSWORD=c1oudc0w

export BAT_INFRASTRUCTURE=warden
export BAT_NETWORKING=manual

echo "running BATS..."
bundle exec rspec spec
