#!/bin/bash

set -e -x

BOSH_DIRECTOR=`cat director-info/director-info`
STEMCELL_VERSION=`cat stemcell-version/stemcell-version`

pushd light-stemcell
    LIGHT_STEMCELL=`ls *.tgz`
    STEMCELL_PATH=$PWD/$LIGHT_STEMCELL
    mkdir -p /tmp/ci-artifacts/softlayer/dynamic/ubuntu/trusty/go/deployments/
    cp ${STEMCELL_PATH} /tmp/ci-artifacts/softlayer/dynamic/ubuntu/trusty/go/deployments/
popd

cd bosh

bosh -n target ${BOSH_DIRECTOR}
bosh -n login admin admin

director_uuid=$(bosh -n status --uuid)

spec_path=$PWD/bat.yaml

cat > $spec_path << EOF
---
cpi: softlayer
properties:
  uuid: $director_uuid
  stemcell:
    name: ${LIGHT_STEMCELL%.*}
    version: latest
  cloud_properties:
    bosh_ip: ${BOSH_DIRECTOR}
    public_vlan_id: 524956
    private_vlan_id: 524954
    data_center: lon02
    vm_name_prefix: env2a-boshmicrotest-
    domain: softlayer.com
  pool_size: 1
  instances: 1
  second_static_ip: 159.122.235.232
  networks:
  - name: default
    type: dynamic
  batlight:
    missing: nope
EOF

# Set up env vars used by BATS
export BAT_DEPLOYMENT_SPEC=$spec_path
export BAT_STEMCELL=$STEMCELL_PATH
export BAT_DIRECTOR=${BOSH_DIRECTOR}
export BAT_DNS_HOST=${BOSH_DIRECTOR}
export BAT_VCAP_PASSWORD=c1oudc0w

export BAT_INFRASTRUCTURE=softlayer
export BAT_NETWORKING=dynamic

export STEMCELL_BUILD_NUMBER=${STEMCELL_VERSION}

export BOSH_SOFTLAYER_MICROBOSH_IP=${BOSH_DIRECTOR}
export BOSH_SOFTLAYER_BAT_DEPLOYMENT_SPEC=$spec_path

echo "running BATS..."
bundle exec rake spec:system:existing_micro[softlayer, esxi, ubuntu, trusty, dynamic, go, true, ovf]

