#!/bin/bash

(
  set -e

  echo -e "\n Get stemcell version... "
  STEMCELL_VERSION=`cat vsphere-stemcell/version`

  # output stemcell-version to update to s3 bucket
  mkdir out
  OUTPUT_DIR=$PWD/out

  echo -e "\n Navigate to vagrant directory..."
  cd bosh/bosh-stemcell

  echo -e "\n Copy s3cfg to vagrant shared directory..."
  cp ../../bosh-softlayer-private/.s3cfg .

  echo -e "\n Bring up vagrant stemcell building VM for AWS EC2-Classic..."
  vagrant up remote --provider=aws

  echo -e "\n Build stemcell, then upload to S3 bucket..."
  vagrant ssh -c "
    cd /bosh
    bundle
    CANDIDATE_BUILD_NUMBER=${STEMCELL_VERSION}
    bundle exec rake stemcell:build[softlayer,hyperv,ubuntu,trusty,go,bosh-os-images,bosh-ubuntu-trusty-os-image.tgz]
    cd tmp
    md5sum *.tgz > files.md5
  " remote

  vagrant scp remote:/bosh/tmp/files.md5 $OUTPUT_DIR
  vagrant scp remote:/bosh/tmp/*.tgz $OUTPUT_DIR
  pushd $OUTPUT_DIR
    md5sum *.tgz | diff files.md5 -
  popd

  echo $STEMCELL_VERSION > $OUTPUT_DIR/stemcell-version

  echo -e "\n Terminating VM"
  ec2-describe-instances --filter "key-name=bosh" | grep instance | awk '{print $3}' | xargs ec2-terminate-instances
)
