---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: swayr/slci

inputs:
  - name: timer-2weeks
  - name: bosh-softlayer-stemcells
    path: gopath/src/github.com/maximilien/bosh-softlayer-stemcells

run:
  path: gopath/src/github.com/maximilien/bosh-softlayer-stemcells/ci/scripts/cleanup-stemcells
