---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
  - name: published-stemcell
  - name: bosh-softlayer-stemcells
outputs:
  - name: version
run:
  path: bosh-softlayer-stemcells/ci/tasks/make-stemcell-version.sh
