---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci
inputs:
- name: published-stemcell
- name: bosh-softlayer-stemcells
run:
  path: bosh-src/ci/pipelines/stemcells/tasks/make-stemcell-version.sh
