---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/azure-cpi-release
inputs:
  - name: bosh-softlayer-stemcells
  - name: bosh-init
  - name: deployment
run:
  path: bosh-softlayer-stemcells/ci/tasks/teardown-director.sh
params:
  BOSH_INIT_LOG_LEVEL:        warn