---
platform: linux
image: docker:///posijon/slci

inputs:
  - name: bosh-softlayer-stemcells
    path: gopath/src/github.com/maximilien/bosh-softlayer-stemcells

run:
  path: gopath/src/github.com/maximilien/bosh-softlayer-stemcells/bin/ci